language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aherriot/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aherriot/docker-react npm run test
